
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: next-webapp
  name: next-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: next-webapp
    spec:
      containers:
        - image: itgain2.azurecr.io/nextjs-docker/nextjs-docker:v1
          name: webapp
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: next-webapp
  labels:
    run: next-webapp
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: next-webapp
  type: LoadBalancer